
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/cyber_shield
    driverClassName: com.mysql.cj.jdbc.Driver
    password: test1234
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB